return {
  -- "echasnovski/mini.snippets",
  -- event = "InsertEnter",
  -- dependencies = "rafamadriz/friendly-snippets",
  -- opts = function()
  --   local mini_snippets = require("mini.snippets")
  --   local gen_loader = mini_snippets.gen_loader
  --
  --   return {
  --     mappings = {
  --       expand = "<C-s>",
  --       jump_next = "<A-;>",
  --       jump_prev = "<A-j>",
  --       stop = "<C-c>", -- можно поменять на <esc>
  --     },
  --     snippets = {
  --       gen_loader.from_file(vim.fn.stdpath("config") .. "/snippets/global.json"),
  --       gen_loader.from_lang(),
  --     },
  --     expand = {
  --       select = MiniSnippets.default_select, -- без лишних переменных
  --     },
  --   }
  -- end,
}
